import {
  defineConfig,
  presetUno,
  presetAttributify,
  presetIcons,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss';

export default defineConfig({
  darkMode: 'class',
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
      extraProperties: { display: 'inline-block', 'vertical-align': 'middle' },
      collections: {
        lucide: () => import('@iconify-json/lucide/icons.json').then((m) => m.default),
      },
    }),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
  shortcuts: {
    'flex-center': 'flex items-center justify-center',
    'flex-between': 'flex items-center justify-between',
    card: 'bg-bg border border-border rounded-xl p-4 shadow-sm',
    'card-hover': 'card hover:shadow-md hover:border-border-hover transition-all duration-200',
    btn: 'inline-flex items-center justify-center rounded-lg px-4 py-2 text-sm font-medium transition-colors focus:outline-none disabled:opacity-50 disabled:pointer-events-none outline-none',
    'btn-primary': 'btn bg-primary text-on-primary hover:opacity-90',
    'btn-secondary': 'btn bg-muted text-fg hover:bg-muted-hover',
    'btn-ghost': 'btn hover:bg-muted',
    'btn-icon': 'btn p-2 rounded-lg',
    input:
      'w-full rounded-lg border border-border bg-bg px-3 py-2 text-sm text-fg placeholder:text-fg-muted focus:border-primary transition-colors outline-none focus:outline-none focus:ring-0',
    textarea: 'input resize-none',
    checkbox: 'h-4 w-4 rounded border-border text-primary focus:ring-primary cursor-pointer',
  },
  theme: {
    colors: {
      fg: 'var(--fg)',
      'fg-muted': 'var(--fg-muted)',
      bg: 'var(--bg)',
      muted: 'var(--muted)',
      'muted-hover': 'var(--muted-hover)',
      border: 'var(--border)',
      'border-hover': 'var(--border-hover)',
      primary: 'var(--primary)',
      'on-primary': 'var(--on-primary)',
      success: 'var(--success)',
      danger: 'var(--danger)',
      overlay: 'var(--overlay)',
    },
  },
  safelist: [
    'i-lucide-video',
    'i-lucide-file-text',
    'i-lucide-check-square',
    'i-lucide-link',
    'i-lucide-github',
    'i-lucide-layers',
    'i-lucide-inbox',
    'i-lucide-plus',
    'i-lucide-search',
    'i-lucide-x',
    'i-lucide-check',
    'i-lucide-trash-2',
    'i-lucide-edit-2',
    'i-lucide-log-out',
    'i-lucide-user',
    'i-lucide-folder',
    'i-lucide-external-link',
    'i-lucide-loader-2',
    'i-lucide-play-circle',
    'i-lucide-arrow-left',
    'i-lucide-folder-x',
    'i-lucide-grip-vertical',
    'i-lucide-sun',
    'i-lucide-moon',
  ],
});
